/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CONNECT PACKING
package MAVLink.bluetooth;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 *  wifi connect 
 */
public class msg_connect extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_CONNECT = 34;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CONNECT;

      
    /**
     * connect to router and mqtt broker
     */
    public short connect;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_CONNECT;
        
        packet.payload.putUnsignedByte(connect);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a connect message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.connect = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_connect() {
        this.msgid = MAVLINK_MSG_ID_CONNECT;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_connect( short connect) {
        this.msgid = MAVLINK_MSG_ID_CONNECT;

        this.connect = connect;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_connect( short connect, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_CONNECT;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.connect = connect;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_connect(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_CONNECT;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_CONNECT - sysid:"+sysid+" compid:"+compid+" connect:"+connect+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_CONNECT";
    }
}
        