/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE BLUETOOTH_CHANGE_NAME PACKING
package MAVLink.bluetooth;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 *  BMWSeat control 
 */
public class msg_bluetooth_change_name extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME = 31;
    public static final int MAVLINK_MSG_LENGTH = 20;
    private static final long serialVersionUID = MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME;

      
    /**
     * change bluetooth device name
     */
    public short name[] = new short[20];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME;
        
        
        for (int i = 0; i < name.length; i++) {
            packet.payload.putUnsignedByte(name[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a bluetooth_change_name message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
         
        for (int i = 0; i < this.name.length; i++) {
            this.name[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_bluetooth_change_name() {
        this.msgid = MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_bluetooth_change_name( short[] name) {
        this.msgid = MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME;

        this.name = name;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_bluetooth_change_name( short[] name, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.name = name;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_bluetooth_change_name(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME - sysid:"+sysid+" compid:"+compid+" name:"+name+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_BLUETOOTH_CHANGE_NAME";
    }
}
        