/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE BL_COMMAND PACKING
package MAVLink.bootloader;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 * Bootloader command
 */
public class msg_bl_command extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_BL_COMMAND = 2;
    public static final int MAVLINK_MSG_LENGTH = 5;
    private static final long serialVersionUID = MAVLINK_MSG_ID_BL_COMMAND;

      
    /**
     * value
     */
    public long value;
      
    /**
     * command
     */
    public short command;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_BL_COMMAND;
        
        packet.payload.putUnsignedInt(value);
        packet.payload.putUnsignedByte(command);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a bl_command message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.value = payload.getUnsignedInt();
        this.command = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_bl_command() {
        this.msgid = MAVLINK_MSG_ID_BL_COMMAND;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_bl_command( long value, short command) {
        this.msgid = MAVLINK_MSG_ID_BL_COMMAND;

        this.value = value;
        this.command = command;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_bl_command( long value, short command, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_BL_COMMAND;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.value = value;
        this.command = command;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_bl_command(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_BL_COMMAND;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_BL_COMMAND - sysid:"+sysid+" compid:"+compid+" value:"+value+" command:"+command+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_BL_COMMAND";
    }
}
        