/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE BL_ACK PACKING
package MAVLink.bootloader;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 *  command and ack back 
 */
public class msg_bl_ack extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_BL_ACK = 1;
    public static final int MAVLINK_MSG_LENGTH = 5;
    private static final long serialVersionUID = MAVLINK_MSG_ID_BL_ACK;

      
    /**
     * counts
     */
    public long value;
      
    /**
     * acknowledge or not
     */
    public short ack_code;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_BL_ACK;
        
        packet.payload.putUnsignedInt(value);
        packet.payload.putUnsignedByte(ack_code);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a bl_ack message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.value = payload.getUnsignedInt();
        this.ack_code = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_bl_ack() {
        this.msgid = MAVLINK_MSG_ID_BL_ACK;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_bl_ack( long value, short ack_code) {
        this.msgid = MAVLINK_MSG_ID_BL_ACK;

        this.value = value;
        this.ack_code = ack_code;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_bl_ack( long value, short ack_code, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_BL_ACK;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.value = value;
        this.ack_code = ack_code;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_bl_ack(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_BL_ACK;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_BL_ACK - sysid:"+sysid+" compid:"+compid+" value:"+value+" ack_code:"+ack_code+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_BL_ACK";
    }
}
        