/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE BL_OTA PACKING
package MAVLink.bootloader;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 * Bootloader command
 */
public class msg_bl_ota extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_BL_OTA = 3;
    public static final int MAVLINK_MSG_LENGTH = 132;
    private static final long serialVersionUID = MAVLINK_MSG_ID_BL_OTA;

      
    /**
     * counts pages
     */
    public int counts;
      
    /**
     * checksum
     */
    public int checksum;
      
    /**
     * ota
     */
    public short value[] = new short[128];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_BL_OTA;
        
        packet.payload.putUnsignedShort(counts);
        packet.payload.putUnsignedShort(checksum);
        
        for (int i = 0; i < value.length; i++) {
            packet.payload.putUnsignedByte(value[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a bl_ota message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.counts = payload.getUnsignedShort();
        this.checksum = payload.getUnsignedShort();
         
        for (int i = 0; i < this.value.length; i++) {
            this.value[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_bl_ota() {
        this.msgid = MAVLINK_MSG_ID_BL_OTA;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_bl_ota( int counts, int checksum, short[] value) {
        this.msgid = MAVLINK_MSG_ID_BL_OTA;

        this.counts = counts;
        this.checksum = checksum;
        this.value = value;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_bl_ota( int counts, int checksum, short[] value, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_BL_OTA;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.counts = counts;
        this.checksum = checksum;
        this.value = value;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_bl_ota(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_BL_OTA;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_BL_OTA - sysid:"+sysid+" compid:"+compid+" counts:"+counts+" checksum:"+checksum+" value:"+value+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_BL_OTA";
    }
}
        