/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE LOGGER_CODE PACKING
package MAVLink.logger;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 * Logger code
 */
public class msg_logger_code extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_LOGGER_CODE = 20;
    public static final int MAVLINK_MSG_LENGTH = 4;
    private static final long serialVersionUID = MAVLINK_MSG_ID_LOGGER_CODE;

      
    /**
     * uint32_t
     */
    public long log_code;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_LOGGER_CODE;
        
        packet.payload.putUnsignedInt(log_code);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a logger_code message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.log_code = payload.getUnsignedInt();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_logger_code() {
        this.msgid = MAVLINK_MSG_ID_LOGGER_CODE;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_logger_code( long log_code) {
        this.msgid = MAVLINK_MSG_ID_LOGGER_CODE;

        this.log_code = log_code;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_logger_code( long log_code, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_LOGGER_CODE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.log_code = log_code;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_logger_code(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_LOGGER_CODE;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_LOGGER_CODE - sysid:"+sysid+" compid:"+compid+" log_code:"+log_code+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_LOGGER_CODE";
    }
}
        