/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CONNECTION PACKING
package MAVLink.smartmattress;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 * Connection
 */
public class msg_connection extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_CONNECTION = 55;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CONNECTION;

      
    /**
     * set, get ack
     */
    public short pk_type;
      
    /**
     * 0x00
     */
    public short sub_bed;
      
    /**
     * 0x01/0x01
     */
    public short pos;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_CONNECTION;
        
        packet.payload.putUnsignedByte(pk_type);
        packet.payload.putUnsignedByte(sub_bed);
        packet.payload.putUnsignedByte(pos);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a connection message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.pk_type = payload.getUnsignedByte();
        this.sub_bed = payload.getUnsignedByte();
        this.pos = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_connection() {
        this.msgid = MAVLINK_MSG_ID_CONNECTION;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_connection( short pk_type, short sub_bed, short pos) {
        this.msgid = MAVLINK_MSG_ID_CONNECTION;

        this.pk_type = pk_type;
        this.sub_bed = sub_bed;
        this.pos = pos;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_connection( short pk_type, short sub_bed, short pos, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_CONNECTION;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.pk_type = pk_type;
        this.sub_bed = sub_bed;
        this.pos = pos;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_connection(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_CONNECTION;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_CONNECTION - sysid:"+sysid+" compid:"+compid+" pk_type:"+pk_type+" sub_bed:"+sub_bed+" pos:"+pos+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_CONNECTION";
    }
}
        