/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE PRESSURE PACKING
package MAVLink.smartmattress;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 * mattress pressure sensor
 */
public class msg_pressure extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_PRESSURE = 56;
    public static final int MAVLINK_MSG_LENGTH = 92;
    private static final long serialVersionUID = MAVLINK_MSG_ID_PRESSURE;

      
    /**
     * uint32_t
     */
    public long timestamp;
      
    /**
     * uint32_t[22]
     */
    public long pressure[] = new long[22];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_PRESSURE;
        
        packet.payload.putUnsignedInt(timestamp);
        
        for (int i = 0; i < pressure.length; i++) {
            packet.payload.putUnsignedInt(pressure[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a pressure message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.timestamp = payload.getUnsignedInt();
         
        for (int i = 0; i < this.pressure.length; i++) {
            this.pressure[i] = payload.getUnsignedInt();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_pressure() {
        this.msgid = MAVLINK_MSG_ID_PRESSURE;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_pressure( long timestamp, long[] pressure) {
        this.msgid = MAVLINK_MSG_ID_PRESSURE;

        this.timestamp = timestamp;
        this.pressure = pressure;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_pressure( long timestamp, long[] pressure, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_PRESSURE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.timestamp = timestamp;
        this.pressure = pressure;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_pressure(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_PRESSURE;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_PRESSURE - sysid:"+sysid+" compid:"+compid+" timestamp:"+timestamp+" pressure:"+pressure+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_PRESSURE";
    }
}
        