/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CONTROL_STEP PACKING
package MAVLink.smartmattress;
import MAVLink.MAVLinkPacket;
import MAVLink.Messages.MAVLinkMessage;
import MAVLink.Messages.MAVLinkPayload;
        
/**
 * control stepper motor
 */
public class msg_control_step extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_CONTROL_STEP = 61;
    public static final int MAVLINK_MSG_LENGTH = 5;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CONTROL_STEP;

      
    /**
     * positive to rotate cw, negative to rotate ccw
     */
    public int steps;
      
    /**
     * stepper motor id
     */
    public short step_id;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_CONTROL_STEP;
        
        packet.payload.putInt(steps);
        packet.payload.putUnsignedByte(step_id);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a control_step message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.steps = payload.getInt();
        this.step_id = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_control_step() {
        this.msgid = MAVLINK_MSG_ID_CONTROL_STEP;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_control_step( int steps, short step_id) {
        this.msgid = MAVLINK_MSG_ID_CONTROL_STEP;

        this.steps = steps;
        this.step_id = step_id;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_control_step( int steps, short step_id, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_CONTROL_STEP;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.steps = steps;
        this.step_id = step_id;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_control_step(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_CONTROL_STEP;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_CONTROL_STEP - sysid:"+sysid+" compid:"+compid+" steps:"+steps+" step_id:"+step_id+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_CONTROL_STEP";
    }
}
        